### ISSUE TITLE
write a priority queue for Poisson mix strategy

### ISSUE THREAD

**Issue by david415** [Katzenpost/core#7]
we need an efficient disk-backed priority queue for the mixing

**Comment by david415** [comment]
This blog post outlines what I think is the correct approach, priority queue access via golang channels:
https://husobee.github.io/heaps/golang/safe/2016/09/01/safe-heaps-golang.html

We definitely do not want to use their code for two reasons:
1. there's no software license
2. they use interface{} and we don't need this implementation to be "generic". We only need it to work with Sphinx packets which will be represented by []byte.

**Comment by Yawning** [comment]
I'll take this now.

The "right" thing to do long term is to implement something similar to the system described in the paper:
[Peter Sanders. Fast Priority Queues for Cached Memory](http://people.mpi-inf.mpg.de/~sanders/papers/falenex.ps.gz), as the working set of a production system is likely to far exceed that which can fit into RAM.

A working implementation can be found as a C++ template library as part of [stxxl](https://stxxl.org/tags/1.4.1/design_pqueue.html), but the code is fairly complicated and cgo while possibly ok (since I'm planning on using a single thread for scheduling) leads to sadness down the road.

**Comment by Yawning** [comment]
The entirely-in-memory just to make forward progress version of this is done now.  I'll merge it later today, and carve off "make it support huge datasets" into a separate issue.
